### ISSUE TITLE
Not all names corrected

### ISSUE THREAD

**Issue by NathanielB2** [enricodias/nameize#1]
Tri vu phu should be Tri Vu Phu
Carlo D'ippoliti should be Carlo D'Ippoliti
Kerényi ádám should be Kerényi Ádám
Matteo Dell'aqcua should be Matteo Dell'Aqcua
Shuanping dai should be Shuanping Dai  

What can I do to fix this?

**Comment by enricodias** [comment]
All of those are working except `Tri vu phu` and `Shuanping dai`.

Although some Asian names may require the capitalization on 2 and 3 letter words, occidental names usually don't. A possible solution to this issue would be a new attribute to force capitalization of such words. You may detect the users' country in your application and pass the appropriate attribute to capitalize their names.

I'll be adding this feature in the next days.
